// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package set

import "sync"

type IntSet struct {
	items map[int]bool
	lock  sync.RWMutex
}

func (s *IntSet) Add(t int) *IntSet {
	s.lock.Lock()
	defer s.lock.Unlock()
	if s.items == nil {
		s.items = make(map[int]bool)
	}

	_, ok := s.items[t]

	if !ok {
		s.items[t] = true
	}
	return s
}

func (s *IntSet) Clear() {

	s.lock.Lock()
	defer s.lock.Unlock()

	s.items = make(map[int]bool)
}

func (s *IntSet) Delete(item int) bool {

	s.lock.Lock()
	defer s.lock.Unlock()

	_, ok := s.items[item]

	if ok {
		delete(s.items, item)
	}
	return ok
}

func (s *IntSet) Has(item int) bool {
	s.lock.Lock()
	defer s.lock.Unlock()

	_, ok := s.items[item]

	return ok
}

func (s *IntSet) Ints() []int {

	s.lock.Lock()
	defer s.lock.Unlock()

	items := []int{}

	for i := range s.items {
		items = append(items, i)
	}

	return items
}

func (s *IntSet) Size() int {
	s.lock.Lock()
	defer s.lock.Unlock()

	return len(s.items)
}
