// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package set

import "sync"

type RuneSet struct {
	items map[rune]bool
	lock  sync.RWMutex
}

func (s *RuneSet) Add(t rune) *RuneSet {
	s.lock.Lock()
	defer s.lock.Unlock()
	if s.items == nil {
		s.items = make(map[rune]bool)
	}

	_, ok := s.items[t]

	if !ok {
		s.items[t] = true
	}
	return s
}

func (s *RuneSet) Clear() {

	s.lock.Lock()
	defer s.lock.Unlock()

	s.items = make(map[rune]bool)
}

func (s *RuneSet) Delete(item rune) bool {

	s.lock.Lock()
	defer s.lock.Unlock()

	_, ok := s.items[item]

	if ok {
		delete(s.items, item)
	}
	return ok
}

func (s *RuneSet) Has(item rune) bool {
	s.lock.Lock()
	defer s.lock.Unlock()

	_, ok := s.items[item]

	return ok
}

func (s *RuneSet) Runes() []rune {

	s.lock.Lock()
	defer s.lock.Unlock()

	items := []rune{}

	for i := range s.items {
		items = append(items, i)
	}

	return items
}

func (s *RuneSet) Size() int {
	s.lock.Lock()
	defer s.lock.Unlock()

	return len(s.items)
}
